export { InfraIcon } from './infraIcon';
export { RolesIcon } from './rolesIcon';
export { SheduleIcon } from './sheduleIcon';
export { UploadIcon } from './uploadIcon';
export { UserIcon } from './userIcon';
export { CakeIcon } from './cakeIcon';
export { LocationIcon } from './locationIcon';
export { ClockIcon } from './clockIcon';
export { SearchIcon } from './searchIcon';
export { PdfIcon } from './pdfIcon';
export { CloudUploadIcon } from './cloudUploadIcon'
export { GalleryIcon } from './galleryIcon'
export { CloseIcon } from './closeIcon'